// Mock data shaped exactly to AnalyzeContractPayload schema.
// One realistic-feeling SaaS MSA with a mix of risk levels and one error.

window.MOCK_PAYLOAD = {
  summary: {
    clause_count: 14,
    analysed: 13,
    risky: 6,
    high: 2,
    medium: 3,
    low: 1,
  },
  errors: [
    { clause_id: "c-008", error: "explain_clause: model timeout after 30s" },
  ],
  clauses: [
    {
      id: "c-001",
      section_title: "1. Definitions",
      text: "“Confidential Information” means any information disclosed by either party, whether orally or in writing, that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure.",
      word_count: 41,
      char_start: 0,
      char_end: 268,
      analysis: {
        risk_category: "definitions_standard",
        risk_category_label: "Standard definitions",
        risk_level: "low",
        is_risky: false,
        llm_confidence: 0.94,
        confidence: 0.91,
        short_rationale: "Boilerplate definition language; no unusual scope.",
        rationale_text: "This clause uses a widely-adopted formulation for confidential information. Both written and oral disclosures are covered, and the standard 'reasonably should be understood' catch-all is present. No carve-outs are unusual.",
        attribution: null,
        top_tokens: [],
      },
    },
    {
      id: "c-002",
      section_title: "3. Term and Termination",
      text: "This Agreement shall commence on the Effective Date and continue for an initial term of three (3) years, after which it shall automatically renew for successive one (1) year periods unless either party provides written notice of non-renewal at least ninety (90) days prior to the end of the then-current term.",
      word_count: 52,
      char_start: 612,
      char_end: 920,
      analysis: {
        risk_category: "auto_renewal",
        risk_category_label: "Auto-renewal with long notice window",
        risk_level: "medium",
        is_risky: true,
        llm_confidence: 0.88,
        confidence: 0.85,
        short_rationale: "Auto-renews unless 90-day notice is given.",
        rationale_text: "The contract auto-renews for one-year terms unless either party gives 90 days' written notice before the current term ends. A 90-day window is on the longer side; a missed deadline locks you in for another full year. Calendar this carefully or negotiate down to 30–60 days.",
        attribution: {
          output: "auto-renews unless 90-day notice",
          tokens: [
            { token: "automatically renew", score: 0.92, start: 138, end: 157 },
            { token: "ninety (90) days", score: 0.88, start: 245, end: 261 },
            { token: "non-renewal", score: 0.71, start: 222, end: 233 },
          ],
        },
        top_tokens: [
          { token: "automatically renew", score: 0.92, start: 138, end: 157 },
          { token: "ninety (90) days", score: 0.88, start: 245, end: 261 },
          { token: "non-renewal", score: 0.71, start: 222, end: 233 },
          { token: "successive one (1) year", score: 0.64, start: 175, end: 198 },
        ],
      },
    },
    {
      id: "c-003",
      section_title: "4. Fees and Payment",
      text: "Customer shall pay all undisputed invoices within thirty (30) days of receipt. Vendor reserves the right to increase fees by up to fifteen percent (15%) annually upon thirty (30) days' written notice, with no cap on cumulative increases over the life of the Agreement.",
      word_count: 45,
      char_start: 1180,
      char_end: 1448,
      analysis: {
        risk_category: "uncapped_price_increase",
        risk_category_label: "Uncapped price increases",
        risk_level: "high",
        is_risky: true,
        llm_confidence: 0.96,
        confidence: 0.94,
        short_rationale: "15% annual fee increase with no cumulative cap.",
        rationale_text: "Vendor may raise fees up to 15% per year on 30 days' notice, with no overall ceiling. Compounded over a 3-year term that's a 52% total increase; over 5 years, more than double. There is no opt-out termination tied to the increase. Push for a CPI-linked cap and a termination right if the increase exceeds a threshold.",
        attribution: {
          output: "15% annual increase, no cap",
          tokens: [
            { token: "fifteen percent (15%)", score: 0.97, start: 124, end: 145 },
            { token: "annually", score: 0.83, start: 146, end: 154 },
            { token: "no cap", score: 0.95, start: 197, end: 203 },
            { token: "cumulative increases", score: 0.79, start: 208, end: 228 },
          ],
        },
        top_tokens: [
          { token: "fifteen percent (15%)", score: 0.97, start: 124, end: 145 },
          { token: "no cap", score: 0.95, start: 197, end: 203 },
          { token: "annually", score: 0.83, start: 146, end: 154 },
          { token: "cumulative increases", score: 0.79, start: 208, end: 228 },
          { token: "thirty (30) days", score: 0.42, start: 41, end: 57 },
        ],
      },
    },
    {
      id: "c-004",
      section_title: "5. Intellectual Property",
      text: "All pre-existing intellectual property of each party shall remain the sole property of that party. Any feedback, suggestions, or ideas provided by Customer regarding the Services shall be owned by Vendor and may be used by Vendor for any purpose without compensation or attribution to Customer.",
      word_count: 47,
      char_start: 1610,
      char_end: 1900,
      analysis: {
        risk_category: "feedback_assignment",
        risk_category_label: "Feedback assignment to vendor",
        risk_level: "medium",
        is_risky: true,
        llm_confidence: 0.82,
        confidence: 0.80,
        short_rationale: "Customer feedback is assigned to vendor with no compensation.",
        rationale_text: "Any feedback Customer provides — including detailed bug reports or feature ideas — becomes Vendor's property to use freely. This is common but worth flagging if Customer's team will be deeply integrated with the product roadmap.",
        attribution: {
          output: "feedback owned by vendor",
          tokens: [
            { token: "owned by Vendor", score: 0.91, start: 188, end: 203 },
            { token: "any purpose", score: 0.74, start: 226, end: 237 },
            { token: "without compensation", score: 0.81, start: 238, end: 258 },
          ],
        },
        top_tokens: [
          { token: "owned by Vendor", score: 0.91, start: 188, end: 203 },
          { token: "without compensation", score: 0.81, start: 238, end: 258 },
          { token: "any purpose", score: 0.74, start: 226, end: 237 },
        ],
      },
    },
    {
      id: "c-005",
      section_title: "6. Warranties",
      text: "Vendor warrants that the Services will perform substantially in accordance with the Documentation for a period of thirty (30) days following initial delivery. EXCEPT AS EXPRESSLY SET FORTH HEREIN, THE SERVICES ARE PROVIDED “AS IS” AND VENDOR DISCLAIMS ALL OTHER WARRANTIES, EXPRESS OR IMPLIED.",
      word_count: 47,
      char_start: 2050,
      char_end: 2342,
      analysis: {
        risk_category: "warranty_disclaimer_short",
        risk_category_label: "30-day warranty + broad disclaimer",
        risk_level: "medium",
        is_risky: true,
        llm_confidence: 0.86,
        confidence: 0.83,
        short_rationale: "Warranty period is only 30 days; everything else disclaimed.",
        rationale_text: "Active warranty lasts only 30 days from delivery, after which the service is provided 'as-is' with all implied warranties disclaimed. For an ongoing SaaS, a 30-day window is unusually short — push for a continuous performance warranty tied to the SLA.",
        attribution: {
          output: "30-day warranty, then as-is",
          tokens: [
            { token: "thirty (30) days", score: 0.89, start: 109, end: 125 },
            { token: "AS IS", score: 0.93, start: 215, end: 220 },
            { token: "DISCLAIMS ALL OTHER WARRANTIES", score: 0.87, start: 234, end: 264 },
          ],
        },
        top_tokens: [
          { token: "AS IS", score: 0.93, start: 215, end: 220 },
          { token: "thirty (30) days", score: 0.89, start: 109, end: 125 },
          { token: "DISCLAIMS ALL OTHER WARRANTIES", score: 0.87, start: 234, end: 264 },
        ],
      },
    },
    {
      id: "c-006",
      section_title: "7. Limitation of Liability",
      text: "IN NO EVENT SHALL VENDOR'S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT EXCEED THE FEES PAID BY CUSTOMER TO VENDOR IN THE THREE (3) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM. IN NO EVENT SHALL EITHER PARTY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES.",
      word_count: 53,
      char_start: 2480,
      char_end: 2800,
      analysis: {
        risk_category: "low_liability_cap",
        risk_category_label: "Liability cap is unusually low",
        risk_level: "high",
        is_risky: true,
        llm_confidence: 0.95,
        confidence: 0.93,
        short_rationale: "Cap is only 3 months of fees. Industry norm is 12 months.",
        rationale_text: "Vendor's total liability is capped at fees paid in the 3 months before the claim. Industry standard for enterprise SaaS is 12 months. For a $200k/year contract, this is the difference between $50k and $200k of recovery on a serious breach. Negotiate up, and carve out IP indemnity, breach of confidentiality, and gross negligence from the cap.",
        attribution: {
          output: "3-month liability cap (vs 12-month norm)",
          tokens: [
            { token: "THREE (3) MONTHS", score: 0.98, start: 138, end: 154 },
            { token: "AGGREGATE LIABILITY", score: 0.79, start: 26, end: 45 },
            { token: "EXCEED THE FEES PAID", score: 0.72, start: 91, end: 111 },
            { token: "INDIRECT, INCIDENTAL", score: 0.55, start: 261, end: 281 },
          ],
        },
        top_tokens: [
          { token: "THREE (3) MONTHS", score: 0.98, start: 138, end: 154 },
          { token: "AGGREGATE LIABILITY", score: 0.79, start: 26, end: 45 },
          { token: "EXCEED THE FEES PAID", score: 0.72, start: 91, end: 111 },
          { token: "INDIRECT, INCIDENTAL", score: 0.55, start: 261, end: 281 },
        ],
      },
    },
    {
      id: "c-007",
      section_title: "8. Indemnification",
      text: "Vendor shall defend, indemnify, and hold harmless Customer from and against any third-party claims alleging that the Services infringe such third party's intellectual property rights, provided that Customer promptly notifies Vendor of the claim and provides reasonable cooperation.",
      word_count: 41,
      char_start: 2950,
      char_end: 3232,
      analysis: {
        risk_category: "ip_indemnity_standard",
        risk_category_label: "Standard IP indemnity",
        risk_level: "low",
        is_risky: false,
        llm_confidence: 0.91,
        confidence: 0.89,
        short_rationale: "Standard third-party IP infringement indemnity.",
        rationale_text: "Vendor defends Customer against third-party IP infringement claims. The notice and cooperation conditions are standard. No unusual carve-outs.",
        attribution: null,
        top_tokens: [
          { token: "defend, indemnify", score: 0.62, start: 7, end: 24 },
          { token: "intellectual property", score: 0.51, start: 145, end: 166 },
        ],
      },
    },
    {
      id: "c-008",
      section_title: "9. Data Processing",
      text: "Vendor shall process Customer Data in accordance with the Data Processing Addendum attached hereto as Exhibit B, which is incorporated by reference. Vendor may use aggregated, anonymized usage data for any business purpose.",
      word_count: 36,
      char_start: 3380,
      char_end: 3603,
      analysis: null,
    },
    {
      id: "c-009",
      section_title: "10. Service Levels",
      text: "Vendor shall use commercially reasonable efforts to maintain Service availability of 99.5% measured monthly, excluding scheduled maintenance and Force Majeure events. Customer's sole remedy for failure to meet this target shall be a service credit equal to 5% of the monthly fee, up to a maximum of 20% per month.",
      word_count: 51,
      char_start: 3760,
      char_end: 4072,
      analysis: {
        risk_category: "weak_sla_remedies",
        risk_category_label: "Weak SLA remedies",
        risk_level: "medium",
        is_risky: true,
        llm_confidence: 0.84,
        confidence: 0.82,
        short_rationale: "99.5% SLA with capped service credits as sole remedy.",
        rationale_text: "99.5% monthly availability allows up to 3.6 hours of downtime per month. Service credits are capped at 20% of the monthly fee — and credits are Customer's only remedy. For a business-critical service, push for 99.9%, the right to terminate after repeated misses, and credits that don't preclude other remedies.",
        attribution: {
          output: "99.5% SLA, capped credits as sole remedy",
          tokens: [
            { token: "99.5%", score: 0.91, start: 84, end: 89 },
            { token: "sole remedy", score: 0.93, start: 196, end: 207 },
            { token: "5% of the monthly fee", score: 0.78, start: 247, end: 268 },
            { token: "maximum of 20%", score: 0.71, start: 286, end: 300 },
          ],
        },
        top_tokens: [
          { token: "sole remedy", score: 0.93, start: 196, end: 207 },
          { token: "99.5%", score: 0.91, start: 84, end: 89 },
          { token: "5% of the monthly fee", score: 0.78, start: 247, end: 268 },
          { token: "maximum of 20%", score: 0.71, start: 286, end: 300 },
        ],
      },
    },
    {
      id: "c-010",
      section_title: "11. Confidentiality",
      text: "Each party shall hold the other party's Confidential Information in strict confidence and shall not use or disclose it except as necessary to perform its obligations under this Agreement. Obligations survive for five (5) years after termination.",
      word_count: 39,
      char_start: 4220,
      char_end: 4462,
      analysis: {
        risk_category: "confidentiality_standard",
        risk_category_label: "Standard mutual confidentiality",
        risk_level: "low",
        is_risky: false,
        llm_confidence: 0.93,
        confidence: 0.90,
        short_rationale: "Mutual confidentiality, 5-year tail.",
        rationale_text: "Symmetric confidentiality obligation, surviving 5 years post-termination. Standard for commercial agreements.",
        attribution: null,
        top_tokens: [],
      },
    },
    {
      id: "c-011",
      section_title: "12. Governing Law",
      text: "This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of laws principles. Any dispute shall be resolved exclusively in the state or federal courts located in New Castle County, Delaware, and the parties consent to personal jurisdiction therein.",
      word_count: 50,
      char_start: 4600,
      char_end: 4920,
      analysis: {
        risk_category: "governing_law_standard",
        risk_category_label: "Standard governing law",
        risk_level: "low",
        is_risky: false,
        llm_confidence: 0.92,
        confidence: 0.90,
        short_rationale: "Delaware law, Delaware venue. Common for vendor-side contracts.",
        rationale_text: "Delaware law and exclusive Delaware venue is standard for US SaaS vendors. Acceptable unless Customer has a strong preference for home venue.",
        attribution: null,
        top_tokens: [],
      },
    },
    {
      id: "c-012",
      section_title: "13. Assignment",
      text: "Neither party may assign this Agreement without the prior written consent of the other party, except that Vendor may assign this Agreement without consent to a successor in interest in connection with a merger, acquisition, or sale of all or substantially all of its assets.",
      word_count: 46,
      char_start: 5060,
      char_end: 5333,
      analysis: {
        risk_category: "asymmetric_assignment",
        risk_category_label: "Asymmetric assignment rights",
        risk_level: "low",
        is_risky: true,
        llm_confidence: 0.76,
        confidence: 0.74,
        short_rationale: "Vendor can assign on M&A; Customer cannot.",
        rationale_text: "Vendor may assign freely on a change of control; Customer requires consent. Common for vendor-drafted contracts. Worth flagging only if Customer expects to assign in the near term.",
        attribution: {
          output: "vendor-only M&A assignment",
          tokens: [
            { token: "Vendor may assign", score: 0.85, start: 105, end: 122 },
            { token: "without consent", score: 0.79, start: 134, end: 149 },
            { token: "merger, acquisition", score: 0.66, start: 197, end: 216 },
          ],
        },
        top_tokens: [
          { token: "Vendor may assign", score: 0.85, start: 105, end: 122 },
          { token: "without consent", score: 0.79, start: 134, end: 149 },
          { token: "merger, acquisition", score: 0.66, start: 197, end: 216 },
        ],
      },
    },
    {
      id: "c-013",
      section_title: "14. Notices",
      text: "All notices required under this Agreement shall be in writing and delivered by hand, certified mail, or recognized overnight courier to the addresses set forth in the signature block, or by email to legal@vendor.example with confirmation of receipt.",
      word_count: 41,
      char_start: 5470,
      char_end: 5717,
      analysis: {
        risk_category: "notices_standard",
        risk_category_label: "Standard notices",
        risk_level: "low",
        is_risky: false,
        llm_confidence: 0.95,
        confidence: 0.92,
        short_rationale: "Boilerplate notices clause.",
        rationale_text: "Standard methods of delivery. Email permitted with confirmation, which is reasonable.",
        attribution: null,
        top_tokens: [],
      },
    },
    {
      id: "c-014",
      section_title: "15. Entire Agreement",
      text: "This Agreement, together with all Exhibits attached hereto, constitutes the entire agreement between the parties with respect to the subject matter hereof and supersedes all prior agreements, whether written or oral. No modification shall be effective unless in a writing signed by both parties.",
      word_count: 47,
      char_start: 5860,
      char_end: 6155,
      analysis: {
        risk_category: "entire_agreement_standard",
        risk_category_label: "Standard integration clause",
        risk_level: "low",
        is_risky: false,
        llm_confidence: 0.94,
        confidence: 0.91,
        short_rationale: "Standard integration clause.",
        rationale_text: "Boilerplate. Reminder: any side-letters, order forms, or pre-signing emails are not part of the deal unless attached.",
        attribution: null,
        top_tokens: [],
      },
    },
  ],
};
